import logging
from utils.logging_setup import INVITES
import datetime
from discord.ext import commands, tasks

logger = logging.getLogger('endurabot.' + __name__)

def find_invite_by_code(invite_list, code):
    for inv in invite_list:
        if inv.code == code:
            return inv

class invites_creation(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.Cog.listener()
    async def on_invite_create(self, invite):

        logger.log(INVITES, f"Invite [{invite.code}] generated by {invite.inviter} ({invite.inviter.id}).")
        self.bot.invites = await invite.guild.invites()

async def setup(bot):
    await bot.add_cog(invites_creation(bot))